name: Cypress Tests

on:
  push:
    branches: [supabase]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: NPM install
        run: npm ci
        working-directory: app

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: app
          build: npm run build
          start: npm cypress:ci
