on: push
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "git@github.com:Lightbulb-Learning/lightbulb-learning"
          source_branch: "main"
          destination_repo: "git@github.com:Robert-Nickel/lightbulb-learning"
          destination_branch: "main"