on: push
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "lightbulb-learning/lightbulb-learning"
          source_branch: "refs/remotes/source/*"
          destination_repo: "robert-nickel/lightbulb-learning"
          destination_branch: "refs/heads/*"