name: Deploy AWS CDK

# Controls when the action will run.
on:
  push:
    branches: [ main ]
  #pull_request:
  #branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: install npm
        run: "sudo apt update -y && sudo apt install nodejs npm -y"

      - name: install JDK
        run: "sudo apt-get install default-jdk -y"

      - name: download scala
        run: "wget www.scala-lang.org/files/archive/scala-2.13.0.deb"

      - name: install scala
        run: "sudo dpkg -i scala*.deb"

      - name: add sbt repo
        run: "echo deb https://dl.bintray.com/sbt/debian\" | sudo tee -a /etc/apt/sources.list.d/sbt.list"

      - name: add public key
        run: "sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823"

      - name: install SBT
        run: "sudo apt-get install sbt -y"

      - name: test sbt
        run: "sbt test"

      - name: Install AWS CDK
        run: "sudo npm install -g aws-cdk"

      - name: Install CDK dependencies
        run: "sudo npm install"
        working-directory: infrastructure

      - name: CDK Synth
        run: cdk synth
        working-directory: infrastructure

      - name: CDK Deploy
        run: cdk deploy
        working-directory: infrastructure
# inspired by https://github.com/AdminTurnedDevOps/YouTube/blob/main/.github/workflows/main.yml